version: "3.3"

services:
  # Backend API
  app:
    container_name: campaignservice
    build: ./
    working_dir: /app
    # env_file:
    #   - ./server/config/.env
    ports:
      - "3003:3003"
    # command: ["/app/wait-for-postgres.sh", "postgres:5432", "--", "npm", "start"]
